name: Deploy to itch.io

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Package game
        run: zip blaze-the-maze.zip index.html assets -r

      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler

      - name: Push to itch.io
        run: ./butler push blaze-the-maze.zip unusual-technologies/blaze-the-maze:html5
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
